# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Set build number
      run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle
      run: ./gradlew :core:build
    - name: Get jar name
      id: file
      run: |
        output="$(find core/build/libs/ -maxdepth 1 -name "*.jar" -type f -printf "%f\n")"
        output=${output%????}
        echo "jarname=$output" >> "$GITHUB_OUTPUT"
    - name: Package application
      run: |
        cd core/build/libs
        zip -r ${{ steps.file.outputs.jarname }}.zip ./*
        ls -al
    - name: Upload to Github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: core/build/libs/${{ steps.file.outputs.jarname }}.zip
        asset_name: ${{ steps.file.outputs.jarname }}+build.${{ github.run_number }}.zip
        asset_content_type: application/zip
    - name: Publish Artifact
      run: ./gradlew :core:publish
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
